say_and_do_task:
    resource: "@SayAndDoTaskBundle/Resources/config/routing.yml"
    prefix:   /task

say_and_do_profile:
    resource: "@SayAndDoProfileBundle/Resources/config/routing.yml"
    prefix:   /

say_and_do_analyzis:
    resource: "@SayAndDoAnalyzisBundle/Resources/config/routing.yml"
    prefix:   /
    
say_and_do_admin:
    resource: "@SayAndDoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

