say_and_do_analyzis_homepage:
    path:     /es/
    defaults: { _controller: SayAndDoAnalyzisBundle:Default:index }

say_and_do_analyzis_homepage.add:
    path:     /es/add
    defaults:
        _controller: SayAndDoAnalyzisBundle:Default:addDocument
    methods:   [POST,GET]

say_and_do_analyzis_homepage.view:
    path:     /es/view/{id}
    defaults:
        _controller: SayAndDoAnalyzisBundle:Default:viewDocument
    methods:   [GET]

say_and_do_analyzis_homepage.remove:
    path:     /es/remove/{id}
    defaults:
        _controller: SayAndDoAnalyzisBundle:Default:removeDocument
    methods:   [GET]

say_and_do_analyzis_homepage.query:
    path:     /es/query
    defaults:
        _controller: SayAndDoAnalyzisBundle:Default:queryDocuments
    methods:   [POST, GET]

say_and_do_analyzis_homepage.init:
    path:     /es/init
    defaults: { _controller: SayAndDoAnalyzisBundle:Default:init }

