say_and_do_profile_homepage:
    path: /
    defaults: { _controller: SayAndDoProfileBundle:Homepage:homepage }

say_and_do_profile_profiles:
    path:     /profiles
    defaults: { _controller: SayAndDoProfileBundle:Profile:index }

say_and_do_profile_details:
    path: /profile/{id}
    defaults:
        _controller: SayAndDoProfileBundle:Profile:details
    methods: [GET]
